config/routes.rb
Rails.application.routes.draw do
  get '/search' => 'search#search'
  devise_for :users, controllers: { registrations: 'users/registrations',sessions: 'users/sessions' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'homes#top'
  get 'home/about' => 'homes#about'

  resources:groups, only: [:new, :index, :show, :create, :edit, :update]
  resources :users, only: [:index, :show, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end

  resources :books, only: [:create, :index, :show, :edit, :update, :destroy] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

  belongs_to :user
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  validates :title, {presence: true}
  validates :body, {presence: true, length: {maximum:200}}

end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book
  validates :comment, {presence: true}
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/group.rb
class Group < ApplicationRecord

  has_many :group_users
  has_many :users, through: :group_users
  validates :name, presence: true, uniqueness: true
  validates :introduction, {presence: true}
end

app/models/group_user.rb
class GroupUser < ApplicationRecord
  
  belongs_to :user
  belongs_to :group
end

app/models/post_comment.rb
class PostComment < ApplicationRecord
  belongs_to :user
  belongs_to :book
  validates :comment, {presence: true}
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
  # class_name: "User"を定義することでUserテーブルのレコードを参照する
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  has_many :group_users
  has_many :groups, through: :group_users

  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :followers, through: :reverse_of_relationships, source: :follower
  # 被フォロー関係を通じて参照→followed_idをフォローしている人
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  # [class_name: "Relationship"]は省略可能
  has_many :followings, through: :relationships, source: :followed
  # 与フォロー関係を通じて参照→follower_idをフォローしている人

  attachment:profile_image

  validates :name, length: { in: 2..20}, presence: true, uniqueness: true
  validates :introduction, length: {maximum:50}

  def follow(user_id)
    relationships.create(followed_id: user_id)
  end

  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end

  def following?(user)
    followings.include?(user)
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  # before_action :ensure_correct_user, {only: [:edit,:update]}

  def index
    @book = Book.new
    @books = Book.all.order(created_at: :desc)
    @user = current_user
  end

  def create
    @book = Book.new
    @books = Book.all.order(created_at: :desc)
    @user = current_user

    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:notice] = "You have created book successfully."
      redirect_to book_path(@book)
    else
      render :index
    end
  end


  def show
    @book = Book.find(params[:id])
    @book_new = Book.new
    @user = @book.user
    @book_comment = BookComment.new
  end

  def edit
    @book = Book.find(params[:id])
    if current_user.id != @book.user.id
      flash[:notice] = "権限がありません"
      redirect_to books_path
    end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = "You have updated book successfully."
      redirect_to book_path(@book.id)
    else
      render :edit
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path

  end



  private

  def book_params
    params.require(:book).permit(:title, :body)
  end


end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController

  def index
    @groups = Group.all
    @book = Book.new
    @user = current_user
  end

  def show
    @group = Group.find(params[:id])
    @book_new = Book.new
    @user = @group.user
  end

  def new
    @group = Group.new
    @group.users << current_user
  end

  def create
    @group = Group.new(group_params)
    if @group.save
      redirect_to groups_path, notice: 'グループを作成しました'
    else
      render :new
    end
  end

  def edit
    @group = Group.find(params[:id])
  end

  def update
    @group = Group.find(params[:id])
    @group.update(group_params)
    redirect_to groups_path
  end

  private

  def group_params
    params.require(:group).permit(:name, :introduction, user_ids: [] )
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController

  def top
  end

  def about
  end

end

app/controllers/search_controller.rb
class SearchController < ApplicationController

  def search
    @model = params["search"]["model"]    #選択したモデルを@modelに代入
    @value = params["search"]["value"]    #検索にかけた文字列（ここではvalue）を@valueに代入
    @how = params["search"]["how"]        #選択した検索方法howを＠howに代入
    @datas = search_for(@how, @model, @value)   #search_forの引数にインスタンス変数を定義、@datasに最終的な検索結果が入ります
  end


  private

  def match(model, value)           #def search_forでhowがmatchだった場合の処理
    if model == 'user'              #modelがuserの場合の処理
      User.where(name: value)       #whereでvalueと完全一致するnameを探す
    elsif model == 'book'
      Book.where(title: value)
    end
  end

  def forward(model, value)
    if model == 'user'
      User.where("name LIKE ?", "#{value}%")
    elsif model == 'book'
      Book.where("title LIKE ?", "#{value}%")
    end
  end

  def backward(model, value)
    if model == 'user'
      User.where("name LIKE ?", "%#{value}")
    elsif model == 'book'
      Book.where("title LIKE ?", "%#{value}")
    end
  end

  def partical(model, value)
    if model == 'user'
      User.where("name LIKE ?", "%#{value}%")
    elsif model == 'book'
      Book.where("title LIKE ?", "%#{value}%")
    end
  end
  
  def search_for(how, model, value)       #searchアクションで定義した情報が引数の入っている
    case how                              #検索方法のhowの中身がどれなのかwhenの条件分岐の中から探す処理
    
    when 'match'
      match(model, value)                 #検索方法の引数に（model, value）を定義している
    when 'forward'                        #例えばhowがmatchの場合は def match の処理に進みます
      forward(model, value)
    when 'backward'
      backward(model, value)
    when 'partical'
      partical(model, value)
    end
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController


  def index
    @book = Book.new
    @books = Book.all.order(created_at: :desc)
    @user = current_user

    @users = User.all
    @user = current_user
  end

  def show
    @user = User.find(params[:id])
    @book = Book.new
    @book_comment = BookComment.new
  end

  def edit
    @user = User.find(params[:id])
    if current_user.id != @user.id
      flash[:notice] = "権限がありません"
      redirect_to user_path(current_user)
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "You have updated user successfully."
      redirect_to user_path(@user.id)
    else
      render :edit
    end
  end



  private
  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/post_comments_helper.rb
module PostCommentsHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def current_user?(user)
    user == current_user
  end
end

app/views/books/_form.html.erb
<%= form_with model: book, local:true do |f| %>
  <label>Title</label><br />
    <%= f.text_field :title %><br />
  <label>Opinion</label><br />
    <%= f.text_area :body %>
  <div class="action">
    <%= f.submit "Create Book", class: 'btn btn-success' %>
  </div>
<% end %>

app/views/books/_info.html.erb
        <h2>User info</h2>
        <%= attachment_image_tag user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %>

        <table class="table">
          <tr>
            <th>name</th>
            <th><%= user.name %></th>
          </tr>
           <tr>
             <th>introduction</th>
             <th><%= user.introduction %></th>
          </tr>
          <tr>
            <th>follows</th>
            <th>
              <%= link_to user_followings_path(user.id) do %>
              <%= user.followings.count %>
              <% end %>
            </th>
          </tr>
          <tr>
            <th>followers</th>
            <th>
              <%= link_to user_followers_path(user.id) do %>
              <%= user.followers.count %>
              <% end %>
            </th>
          </tr>
        </table>
    <% unless current_user?(user) %>
      <% if current_user.following?(user) %>
        <%= link_to user_relationships_path(user.id), class:"btn btn-md btn-block btn-info mt-4", method: :delete do %>フォローを外す<% end %>
      <% else %>
        <%= link_to user_relationships_path(user.id), class:"btn btn-md btn-block btn-success mt-4", method: :post do %>フォローする<% end %>
      <% end %>

      <%= link_to edit_user_path(user), class: "btn btn-outline-secondary btn-block" do %>
          <i class="fas fa-user-cog "></i>
      <% end %>
    <% end %>

app/views/books/_list.html.erb
<div class="container px-5 px-0">
  <div class="row">
    <div class="col-md-3">
    <% if book.errors.any? %>
      <%= book.errors.count %>error prohibited this obj from being saved:
      <% book.errors.full_messages.each do |message| %>
        <%= message %>
      <% end %>
    <% end %>
        <h2>User info</h2>
        <%= attachment_image_tag user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %>

        <table class="table">
          <tr>
            <th>name</th>
            <th><%= user.name %></th>
          </tr>
           <tr>
             <th>introduction</th>
            <th><%= user.introduction %></th>
          </tr>
        </table>

    <!--% if book.user.id == current_user.id %>-->
      <%= link_to edit_user_path(user), class: "btn btn-outline-secondary btn-block" do %>
          <i class="fas fa-user-cog "></i>
      <% end %>
    <!--% end %>-->
        <h2 class="mt-3">New book</h2>
        <%= form_with model: book, local:true do |f| %>
          <label>Title</label><br />
          <%= f.text_field :title %><br />
           <label>Opinion</label><br />
           <%= f.text_area :body %>
           <div class="action">
             <%= f.submit "Create Book", class: 'btn btn-success' %>
           </div>
         <% end %>
    </div>

app/views/books/edit.html.erb
<div class="container">
  <div class="row">
    <div class="container col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 ">
    <% if @book.errors.any? %>
      <%= @book.errors.count %>error prohibited this obj from being saved:
      <% @book.errors.full_messages.each do |message| %>
        <%= message %>
      <% end %>
    <% end %>
      <h1>Editing Book</h1>
      <%= form_with model: @book, local:true do |f| %>
      <h3>Title</h3>
        <div class="form-group">
        <%= f.text_field :title, class:"form-control", placeholder:"title" %>
        </div>
      <h3>Opinion</h3>
      <div class="form-group">
        <%= f.text_area :body, class:"form-control", placeholder:"body" %>
      </div>
      <hr>
      <div class="form-group">
        <%= f.submit "Update Book", class:"btn btn-lg btn-block btn-info mt-4" %>
      </div>
      <% end %>
      <%= link_to "Show", book_path(@book) %> |
      <%= link_to "Back", books_path %>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<div class="container px-5 px-0">
  <div class="row">
    <div class="col-md-3">
    <%= render 'layouts/errors', obj: @book %>
    <%= render 'books/info', user: @user %>
    <h2 class="mt-3">New book</h2>
    <%= render 'books/form', book: @book %>
    </div>
              <!--左はここまで-->
    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th colspan="3"></th>
          </tr>
          <tbody>
          <% @books.each do |book| %>
            <tr>
              <td>
                <%= link_to user_path(book.user.id) do %>
                <%= attachment_image_tag book.user, :profile_image, :fill, 40, 40, format: 'jpeg', fallback: "no_image.jpg" %>
                <% end %>
              </td>
              <td>
                <%= link_to book_path(book.id) do %>
                <%= book.title %>
                <% end %>
              </td>
              <td><%= book.body %></td>
              <td class="favorite-btn<%= book.id %>">
                <%= render partial: 'favorites/favorite', locals: {book: book} %>
              </td>
              <td>
                コメント件数：<%= book.book_comments.count %>
              </td>
            </tr>
          <% end %>
          </tbody>

        </thead>
      </table>
    </div>
    </div>
</div>

app/views/books/show.html.erb
<div class="container px-5 px-0">
  <div class="row">
    <div class="col-md-3">
    <%= render 'books/info', user: @user %>
    <h2 class="mt-3">New book</h2>
    <%= render 'books/form', book: @book_new %>
    </div>
          <!--左側ここまで-->
    <div class="col-md-8 offset-md-1">
      <h2>Book detail</h2>
      <table class="table">
        <tr>
          <td>
            <%= link_to user_path(@user) do %>
            <%= attachment_image_tag @user, :profile_image, :fill, 40, 40, format: 'jpeg', fallback: "no_image.jpg" %><br />
            <%= @user.name %>
            <% end %>
          </td>
          <td>
            <%= link_to book_path(@book) do %>
            <%= @book.title %>
            <% end %>
          </td>
          <td><%= @book.body %></td>
          <% if @book.user_id == current_user.id %>
          <td>
            <%= link_to edit_book_path(@book), class: "btn btn-sm btn-success" do %>
            Edit
            <% end %>
          </td>
          <td>
            <%= link_to book_path(@book), class: "btn btn-sm btn-danger",
            method: :delete, "data-confirm" => "本当に消しますか？" do %>
            Destroy
            <% end %>
          </td>
          <% end %>
          <td class="favorite-btn<%= @book.id %>">
            <%= render partial: 'favorites/favorite', locals: {book: @book} %>
          </td>
          <td>
            コメント件数：<%= @book.book_comments.count %>
          </td>
        </tr>
      </table>
      <div id="comments_area">
        <%= render partial: 'book_comments/comment', locals: {book: @book, book_comment: @book_comment} %>
      </div>
    </div>
  </div>
</div>

app/views/groups/edit.html.erb
  <div class="containar">
  <div class="row">
    <div class="container col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0">
      <h1>Editing Group</h1>
      <div class="form-body p-4">
        <!--% if @user.errors.any? %>-->
        <!--  %= @user.errors.count %>error prohibited this obj from being saved:-->
        <!--  % @user.errors.full_messages.each do |message| %>-->
        <!--    %= message %>-->
        <!--  % end %>-->
        <!--% end %>-->
        <%= form_with model: @group, local:true do |f| %>
        <h3>グループ名</h3>
          <div class="input-group">
          <%= f.text_field :name, class:"form-control", placeholder:"name" %>
          </div>
        <h3>紹介文</h3>
          <%= f.text_area :introduction, class:"form-control", placeholder:"introduction" %>
          <hr>
        <h3>グループ画像</h3>
          <div class="input-group">
            <!--%= f.attachment_field :profile_image, placeholder: "image" %>-->
          </div>
          <%= f.submit "Update Group", class:"btn btn-lg btn-block btn-info mt-4" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/groups/index.html.erb
<div class="container px-5 px-0">
  <div class="row">
    <div class="col-md-3">
    <%= render 'layouts/errors', obj: @book %>
    <%= render 'books/info', user: @user %>
    <h2 class="mt-3">New book</h2>
    <%= render 'books/form', book: @book %>
    </div>
              <!--左はここまで-->
    <div class="col-md-8 offset-md-1">
      <h2>Groups</h2>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th></th>
            <th>グループ名</th>
            <th>紹介文</th>
            <th colspan="3"></th>
          </tr>
          <tbody>
          <% @groups.each do |group| %>
            <tr>
              <td>
                <!--%= link_to user_path(book.user.id) do %>-->
                <!--%= attachment_image_tag book.user, :profile_image, :fill, 40, 40, format: 'jpeg', fallback: "no_image.jpg" %>-->
                <!--% end %>-->
              </td>
              <td>
                <%= link_to group_path(group.id) do %>
                <%= group.name %>
                <% end %>
              </td>
              <td><%= group.introduction %></td>
              <td>
                <%= link_to edit_group_path(group), class: "btn btn-sm btn-success" do %>
                Edit
                <% end %>
              </td>
            </tr>
          <% end %>
          </tbody>
        </thead>
      </table>
    </div>
    </div>
</div>

app/views/groups/new.html.erb
  <div class="containar">
  <div class="row">
    <div class="container col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0">
      <h1>Create Group</h1>
      <div class="form-body p-4">
        <!--% if @user.errors.any? %>-->
        <!--  %= @user.errors.count %>error prohibited this obj from being saved:-->
        <!--  % @user.errors.full_messages.each do |message| %>-->
        <!--    %= message %>-->
        <!--  % end %>-->
        <!--% end %>-->
        <%= form_with model: @group, local:true do |f| %>
        <h3>グループ名</h3>
          <div class="input-group">
          <%= f.text_field :name, class:"form-control", placeholder:"name" %>
          </div>
        <h3>紹介文</h3>
          <%= f.text_area :introduction, class:"form-control", placeholder:"introduction" %>
          <hr>
        <h3>グループ画像</h3>
          <div class="input-group">
            <!--%= f.attachment_field :profile_image, placeholder: "image" %>-->
          </div>
          <%= f.submit "Create Group", class:"btn btn-lg btn-block btn-info mt-4" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/groups/show.html.erb
<div class="container px-5 px-0">
  <div class="row">
    <div class="col-md-3">
    <%= render 'books/info', user: @user %>
    <h2 class="mt-3">New book</h2>
    <%= render 'books/form', book: @book_new %>
    </div>
          <!--左側ここまで-->
    <div class="col-md-8 offset-md-1">
      <h2>Group Detail</h2>
      <table class="table">
        <tr>
          <td>
            <!--%= link_to user_path(@user) do %>-->
            <!--%= attachment_image_tag @user, :profile_image, :fill, 40, 40, format: 'jpeg', fallback: "no_image.jpg" %><br />-->
            <!--%= @user.name %>-->
            <!--% end %>-->
          </td>
          <td><%= @group.name %></td>
          <td><%= @group.introduction %></td>
          <% if @group.user_id == current_user.id %>
          <td>
            <%= link_to edit_book_path(@group), class: "btn btn-sm btn-success" do %>
            Edit
            <% end %>
          </td>
          <% end %>
        </tr>
      </table>
    </div>
  </div>
</div>