config/routes.rb
Rails.application.routes.draw do
  get '/search' => 'search#search'
  devise_for :users, controllers: { registrations: 'users/registrations',sessions: 'users/sessions' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'homes#top'
  get 'home/about' => 'homes#about'

  resources:groups, only: [:new, :index, :show, :create, :edit, :update]
  resources :users, only: [:index, :show, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end

  resources :books, only: [:create, :index, :show, :edit, :update, :destroy] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

  belongs_to :user
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  validates :title, {presence: true}
  validates :body, {presence: true, length: {maximum:200}}

end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book
  validates :comment, {presence: true}
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/group.rb
class Group < ApplicationRecord

  has_many :group_users
  has_many :users, through: :group_users
  validates :name, presence: true, uniqueness: true
  validates :introduction, {presence: true}
end

app/models/group_user.rb
class GroupUser < ApplicationRecord
  
  belongs_to :user
  belongs_to :group
end

app/models/post_comment.rb
class PostComment < ApplicationRecord
  belongs_to :user
  belongs_to :book
  validates :comment, {presence: true}
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
  # class_name: "User"を定義することでUserテーブルのレコードを参照する
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  has_many :group_users
  has_many :groups, through: :group_users

  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :followers, through: :reverse_of_relationships, source: :follower
  # 被フォロー関係を通じて参照→followed_idをフォローしている人
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  # [class_name: "Relationship"]は省略可能
  has_many :followings, through: :relationships, source: :followed
  # 与フォロー関係を通じて参照→follower_idをフォローしている人

  attachment:profile_image

  validates :name, length: { in: 2..20}, presence: true, uniqueness: true
  validates :introduction, length: {maximum:50}

  def follow(user_id)
    relationships.create(followed_id: user_id)
  end

  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end

  def following?(user)
    followings.include?(user)
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  # before_action :ensure_correct_user, {only: [:edit,:update]}

  def index
    @book = Book.new
    @books = Book.all.order(created_at: :desc)
    @user = current_user
  end

  def create
    @book = Book.new
    @books = Book.all.order(created_at: :desc)
    @user = current_user

    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:notice] = "You have created book successfully."
      redirect_to book_path(@book)
    else
      render :index
    end
  end


  def show
    @book = Book.find(params[:id])
    @book_new = Book.new
    @user = @book.user
    @book_comment = BookComment.new
  end

  def edit
    @book = Book.find(params[:id])
    if current_user.id != @book.user.id
      flash[:notice] = "権限がありません"
      redirect_to books_path
    end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = "You have updated book successfully."
      redirect_to book_path(@book.id)
    else
      render :edit
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path

  end



  private

  def book_params
    params.require(:book).permit(:title, :body)
  end


end

app/controllers/homes_controller.rb
class HomesController < ApplicationController

  def top
  end

  def about
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController


  def index
    @book = Book.new
    @books = Book.all.order(created_at: :desc)
    @user = current_user

    @users = User.all
    @user = current_user
  end

  def show
    @user = User.find(params[:id])
    @book = Book.new
    @book_comment = BookComment.new
  end

  def edit
    @user = User.find(params[:id])
    if current_user.id != @user.id
      flash[:notice] = "権限がありません"
      redirect_to user_path(current_user)
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "You have updated user successfully."
      redirect_to user_path(@user.id)
    else
      render :edit
    end
  end



  private
  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/post_comments_helper.rb
module PostCommentsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def current_user?(user)
    user == current_user
  end
end

app/views/layouts/_errors.html.erb
<% if obj.errors.any? %>
  <div id="error_explanation">
    <h3><%= pluralize(obj.errors.count, "error") %> prohibited this obj from being saved:</h3>
    <ul>
      <% obj.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_header.html.erb
<header>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container">
        <%= link_to root_path, class: "navbar-brand" do %>
        <span>Bookers</span>
        <% end %>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
          <ul class="navbar-nav ml-auto">
          <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to user_path(current_user), class: "nav-link text-light" do %>
            <i class="fas fa-home"></i>
            Home
             <% end %>
          </li>
          <li class="nav-item">
             <%= link_to users_path, class: "nav-link text-light" do %>
             <i class="fas fa-users"></i>
             Users
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to books_path, class: "nav-link text-light" do %>
            <i class="fas fa-book-open"></i>
            Books
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to destroy_user_session_path, method: :delete, class: "nav-link text-light" do %>
            <i class="fas fa-sign-out-alt"></i>
            logout
            <% end %>
          </li>
          <% else %>
            <li class="nav-item">
            <%= link_to root_path, class: "nav-link text-light" do %>
            <i class="fas fa-home"></i> Home
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to home_about_path, class: "nav-link text-light" do %>
            <i class="fas fa-link"></i> About
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to new_user_registration_path, class: "nav-link text-light" do %>
            <i class="fas fa-user-plus"></i> sign up
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to new_user_session_path, class: "nav-link text-light" do %>
            <i class="fas fa-sign-in-alt"></i> login
            <% end %>
          </li>
          <% end %>
          </ul>
        </div>
      </div>
    </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script defer src="https://use.fontawesome.com/releases/v5.15.3/js/all.js" integrity="sha384-haqrlim99xjfMxRP6EWtafs0sB1WKcMdynwZleuUSwJR0mDeRYbhtY+KPMr+JL6f" crossorigin="anonymous"></script>
  </head>

  <body>
    <%= render 'layouts/header' %>
  <main>
    <div class="row">
      <div class="col text-center" style="margin-top: 25px;">
        <% if user_signed_in? %>
          <%= form_with url:search_path, method: :get, local: true do |f| %>
            <%= f.text_field 'search[value]' %>
            <%= f.select 'search[model]', options_for_select({ "User" => "user", "Book" => "book" }) %>
            <%= f.select 'search[how]', options_for_select({ "完全一致" => "match", "前方一致" => "backward", "部分一致" => "partical" }) %>
            <%= f.submit :"検索" %>
          <% end %>
        <% end %>
      </div>
    </div>
    <% if flash[:notice] %>
      <div class="flash">
        <%= flash[:notice] %>
      </div>
    <% end %>

    <%= yield %>
  </main>

  <footer>
    <div class="container mt-5">
      <div class="row">
        <div class="mx-auto">
          <p>CopyRight Infratop.inc</p>
        </div>
      </div>
    </div>
  </footer>

  </body>
</html>